---
# tasks file for roles/app-tier
#- name: Install Apache and start the service
  #hosts: apps
  #become: yes  
  #tasks:
    - name: install {{ payload }}
      package:
       name: "{{ payload }}"
       state: latest
    - name: enable tomcat at boot
      service:
       name: "{{ payload }}"
       enabled: yes

    - name: create ansible tomcat directory
      file:
       path: "{{ tomcat_web_root }}"
       state: directory

    - name: copy static index.html to {{ payload }} webapps/ansible/index.html
      template:
       src: index.html.j2
       dest: "{{ tomcat_web_root }}/index.html" 
       mode: 0644

    - name: restart tomcat
      service:
       name: "{{ payload }}"
       state: started

