---
- name: install {{ payload }}
  yum:
   name=haproxy state=latest

- name: enable {{ payload }} at boot 
  service:
   name: "{{ payload }}"
   enabled: yes

- name: configure {{ payload }}  to load  balance  over app servers
  template:
   src: ./haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg

- name: start {{ payload }}
  service:
   name: "{{ payload }}"
   state: restarted


